django_password/django_password/urls.py
from django.contrib import admin
from django.urls import path,include
from p_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('app/',include('p_app.urls')),
    path('admin/', admin.site.urls),
    path('logout', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

django_password/p_app/urls.py
from django.urls import path
from p_app import views

app_name = 'p_app'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('user_login/',views.user_login, name='user_login'),
]

django_password/p_app/models.py
from django.db import models
from django.contrib.auth.models import User 

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,default=None, 
                              null=True,on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='p_app/profile_pic',blank=True)
    
    def __str__(self):
        return self.user.username

django_password/p_app/forms.py
from django import forms
from django.contrib.auth.models import User
from p_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model=User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

django_password/p_app/views.py
from django.shortcuts import render
from p_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.


def index(request):
    return render(request,'p_app/index.html')

def register(request):
    
    registered = False
    
    if request.method == "POST":
       user_form = UserForm(data=request.POST)
       profile_form=UserProfileInfoForm(data=request.POST)
       
       if user_form.is_valid() and profile_form.is_valid():
           
           user = user_form.save()
           user.set_password(user.password)
           user.save()
           
           profile = profile_form.save(commit=False)
           profile.user = user
           
           if 'profile_pic' in request.FILES:
               profile.profile_pic = request.FILES['profile_pic']
           
           profile.save()
            
           registered = True
            
           
       else:
            print(user_form.errors,profile_form.errors)
            
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'p_app/registration.html', {'user_form':user_form,'profile_form':profile_form,'registered':registered})



@login_required
def special(request):
    return HttpResponse("You are Loged in, Nice")
@login_required
def user_logout(request):
    logout(request)
    #return HttpResponseRedirect('index')
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone trid to login and faild")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'p_app/login.html',{})
        

django_password/templates/p_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'p_app:register' %}">Register</a></li>
          
          {% if user.is_authenticated %}
           <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a></li>
           {% else %}
           <li><a class="navbar-link" href="{% url 'p_app:user_login' %}">LOGIN</a></li>
          {% endif %} 

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body-block %}
      {% endblock %}
    </div>
  </body>
</html>

django_password/templates/p_app/index.html
<!--<!DOCTYPE html>--->
{% extends 'p_app/base.html' %}
{% block body-block %}
 
<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>
 
{% endblock %}

django_password/templates/p_app/login.html
{% extends "p_app/base.html" %}
{% block body-block %}

<div class="jumbotron">
    <h1>please login</h1>
    
    <form action="{% url 'p_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">UserName:</label>
        <input type="text" name="username" placeholder="Enter UserName">
        <label for="password">PassWord</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>

</div>


{% endblock %}

django_password/templates/p_app/registration.html
<!--<!DOCTYPE html>--->
{% extends 'p_app/base.html' %}
{% load static %}
 
{% block body-block %}
 
<div class="jumbotron">
  {% if registered %}
  <h1>Thank You for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}